backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: public/images
public_folder: /images

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "date", widget: "datetime"}

  - name: "hero"
    label: "Hero Section"
    folder: "content/hero"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "text"}
      - {label: "Background Image", name: "backgroundImage", widget: "image", required: false}
      - {label: "CTA Text", name: "ctaText", widget: "string"}
      - {label: "CTA Link", name: "ctaLink", widget: "string"}

  - name: "features"
    label: "Features"
    folder: "content/features"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Icon", name: "icon", widget: "string", hint: "Lucide icon name (e.g., 'heart', 'star', 'check')"}
      - {label: "Order", name: "order", widget: "number", default: 1}

  - name: "settings"
    label: "Site Settings"
    files:
      - label: "General"
        name: "general"
        file: "content/settings/general.md"
        fields:
          - {label: "Site Title", name: "title", widget: "string"}
          - {label: "Site Description", name: "description", widget: "text"}
          - {label: "Logo", name: "logo", widget: "image", required: false}
          - {label: "Favicon", name: "favicon", widget: "image", required: false}
